# Generated by Django 4.2.23 on 2025-08-08 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai_images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('masala', 'Masala Chai'), ('ginger', 'Ginger Chai'), ('cardamom', 'Cardamom Chai'), ('lemon', 'Lemon Chai')], default='masala', max_length=20)),
            ],
        ),
    ]
